spring.application.name=learJPN
spring.datasource.url=jdbc:mysql://localhost:3306/japanese_ai_platform?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=admin123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

jwt.secret=nihonai_super_secure_key_2026_minimum_32_characters_required!!!
jwt.expiration=86400000
openrouter.api.key=${OPENROUTER_API_KEY}